api/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "api"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

crawl/urls.py
from django.urls import path

from . import views


app_name = "crawl"  # 使用 URLconf 命名空间，用于区分不同 app 下的 url


urlpatterns = [
    path("", views.index_view, name="index"),
    path("fetch_view/", views.fetch_view, name="fetch_view"),
    path("remove_view/", views.remove_view, name="remove_view"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# 显示静态文件
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),  # 系统性能监控
    path("backend/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("learn/", include("learn.urls")),
    path("crawl/", include("crawl.urls")),
    path("login/", include("login.urls")),
    path("syscache/", include("sys_cache.urls")),
    path("api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crawl/models.py
from django.db import models
from asgiref.sync import sync_to_async


class BaseKurs(models.Model):
    harga_jual = models.DecimalField(max_digits=12, decimal_places=2)
    harga_beli = models.DecimalField(max_digits=12, decimal_places=2)
    tanggal_dan_waktu = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Dinar(BaseKurs):
    def __str__(self) -> str:
        return f"Dinar: {self.harga_jual}"


class Dirham(BaseKurs):
    def __str__(self) -> str:
        return f"Dirham: {self.harga_jual}"


# 将同步代码改为异步代码

dinar_get_all = sync_to_async(Dinar.objects.all)
dinar_create = sync_to_async(Dinar.objects.create)

dirham_get_all = sync_to_async(Dirham.objects.all)
dirham_create = sync_to_async(Dirham.objects.create)

# 民宿爬虫相关模型
class House(models.Model):
    pass


class Host(models.Model):
    pass


class Labels(models.Model):
    pass


class Facility(models.Model):
    pass


class City(models.Model):
    pass

crawl/views.py
from django.shortcuts import render, redirect

import asyncio
from asgiref.sync import sync_to_async

from .scrapper import get_latest_kurs
from .models import (
    Dinar,
    Dirham,
    dinar_create,
    dinar_get_all,
    dirham_create,
    dirham_get_all,
)

# 异步试图函数


async def index_view(request):

    list_dinar, list_dirham = await asyncio.gather(dinar_get_all(), dirham_get_all())

    context = {"list_dinar": list_dinar, "list_dirham": list_dirham}

    return await sync_to_async(render)(request, "crawl/index.html", context)


async def fetch_view(request):

    kurs = await get_latest_kurs()
    await asyncio.gather(
        dinar_create(
            **{
                "harga_jual": kurs["dinar"]["jual"],
                "harga_beli": kurs["dinar"]["beli"],
            }
        ),
        dirham_create(
            **{
                "harga_jual": kurs["dirham"]["jual"],
                "harga_beli": kurs["dirham"]["beli"],
            }
        ),
    )

    return redirect("crawl:index")


async def remove_view(request):

    await asyncio.gather(
        sync_to_async(Dinar.objects.all().delete)(),
        sync_to_async(Dirham.objects.all().delete)(),
    )

    return redirect("crawl:index")

crawl/templates/crawl/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>巴林第纳尔克换阿联酋迪拉姆</title>
        <link rel="stylesheet" href="https://cdn.jsdeliver.net/npm/bulma@0.8.0/css/bulma.min.css"/>
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    </head>
    <body>
        <section class="section">
            <div class="container">
                <h1 class="title">汇率系统：Dinar（巴林第纳尔）兑换Dirham（阿联酋迪拉姆）</h1>
            </div>
        </section>
        <section class="section">
            <div class="columns">
                <div class="columns is-full">
                    <a href="{% url 'crawl:remove_view' %}" class="button is-danger">全部删除</a>
                    <a href="{% url 'crawl:fetch_view' %}" class="button is-primary">获取新数据</a>
                </div>
            </div>
            <div class="columns">
                <div class="columns is_half">
                    <h4 class="title is-4">Dinar</h4>
                    <div class="columns">
                        <div class="columns is-full">
                            <table class="table">
                                <thead>
                                    <th>日期</th>
                                    <th>销售金额</th>
                                    <th>购买金额</th>
                                </thead>
                                <tbody>
                                    {% for dinar in list_dinar %}
                                    <tr>
                                        <td>{{ dinar.tanggal_dan_waktu }}</td>
                                        <td>{{ dinar.harga_jual }}</td>
                                        <td>{{ dinar.harga_beli }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="columns">
                <div class="columns is_half">
                    <h4 class="title is-4">Dinar</h4>
                    <div class="columns">
                        <div class="columns is-full">
                            <table class="table">
                                <thead>
                                    <th>日期</th>
                                    <th>销售金额</th>
                                    <th>购买金额</th>
                                </thead>
                                <tbody>
                                    {% for dirham in list_dirham %}
                                    <tr>
                                        <td>{{ dirham.tanggal_dan_waktu }}</td>
                                        <td>{{ dirham.harga_jual }}</td>
                                        <td>{{ dirham.harga_beli }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>